"""
The Ledger — Event Upcasters (Phase 4)

Pure functions that transform old event schema versions to current versions
on load. Registered with the UpcasterRegistry in event_store.py.

Design principles:
  - Upcasters are PURE — they never write to the database
  - Raw persisted payload is never modified (immutability guarantee)
  - Transformations are applied transparently by load_stream() / load_all()
  - Missing data is set to None or inferred with documented reasoning
    (fabricating data is worse than null — downstream agents would treat
    fabricated values as real signal)
"""

from __future__ import annotations

from upcasting.registry import UpcasterRegistry

registry = UpcasterRegistry()


# ─── CreditAnalysisCompleted v1 → v2 ─────────────────────────────────────────

@registry.register("CreditAnalysisCompleted", from_version=1)
def upcast_credit_v1_to_v2(payload: dict) -> dict:
    """
    v2 adds three fields to CreditAnalysisCompleted:

    Inference strategy:
      - model_version: "legacy-pre-2026"
        Reason: All v1 events predate the introduction of model versioning.
        We know these were generated by the legacy credit engine.

      - confidence_score: None
        Reason: v1 schema never captured confidence. Setting to None is
        intentional — fabricating a numeric score would be worse because
        downstream agents (DecisionOrchestrator, AgentPerformanceLedger)
        would treat it as real signal, leading to incorrect risk assessments.

      - regulatory_basis: "2025-Q4-GAAP"
        Reason: All v1 events were generated under the 2025-Q4 GAAP baseline
        which was the active regulation before model versioning was introduced.
    """
    return {
        **payload,
        "model_version": "legacy-pre-2026",
        "confidence_score": None,
        "regulatory_basis": "2025-Q4-GAAP",
    }


# ─── DecisionGenerated v1 → v2 ───────────────────────────────────────────────

@registry.register("DecisionGenerated", from_version=1)
def upcast_decision_v1_to_v2(payload: dict) -> dict:
    """
    v2 adds model_versions dict to DecisionGenerated.

    Inference strategy:
      - model_versions: reconstructed from contributing_agent_sessions
        Each session is mapped to "legacy-pre-2026" because v1 events
        predate per-model version tracking.

    Performance note:
      In production, this could require O(N) store lookups for session
      metadata. For offline upcasting (replay/rebuild), this is acceptable.
      For hot-path reads, consider batch-loading sessions.
    """
    model_versions = {}
    for session_id in payload.get("contributing_agent_sessions", []):
        model_versions[session_id] = "legacy-pre-2026"
    return {
        **payload,
        "model_versions": model_versions,
    }
